# Introduction

In this notebook, we will do a comprehensive analysis of the Android app market by comparing thousands of apps in the Google Play store.

# About the Dataset of Google Play Store Apps & Reviews

**Data Source:** <br>
App and review data was scraped from the Google Play Store by Lavanya Gupta in 2018. Original files listed [here](
https://www.kaggle.com/lava18/google-play-store-apps).

# Import Statements

In [ ]:
import pandas as pd
import plotly.express as px

# Notebook Presentation

In [ ]:
# Show numeric output in decimal format e.g., 2.15
pd.options.display.float_format = '{:,.2f}'.format

# Read the Dataset

In [ ]:
df_apps = pd.read_csv('apps.csv')
df_apps

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
0,Ak Parti Yardım Toplama,SOCIAL,NaN,0,8.70,0,Paid,$13.99,Teen,Social,"July 28, 2017",4.1 and up
1,Ain Arabic Kids Alif Ba ta,FAMILY,NaN,0,33.00,0,Paid,$2.99,Everyone,Education,"April 15, 2016",3.0 and up
2,Popsicle Launcher for Android P 9.0 launcher,PERSONALIZATION,NaN,0,5.50,0,Paid,$1.49,Everyone,Personalization,"July 11, 2018",4.2 and up
3,Command & Conquer: Rivals,FAMILY,NaN,0,19.00,0,NaN,0,Everyone 10+,Strategy,"June 28, 2018",Varies with device
4,CX Network,BUSINESS,NaN,0,10.00,0,Free,0,Everyone,Business,"August 6, 2018",4.1 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Subway Surfers,GAME,4.50,27723193,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade,"July 12, 2018",4.1 and up
10837,Subway Surfers,GAME,4.50,27724094,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade,"July 12, 2018",4.1 and up
10838,Subway Surfers,GAME,4.50,27725352,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade,"July 12, 2018",4.1 and up
10839,Subway Surfers,GAME,4.50,27725352,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade,"July 12, 2018",4.1 and up
10840,Subway Surfers,GAME,4.50,27711703,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade,"July 12, 2018",4.1 and up

# Data Cleaning

How many rows and columns does `df_apps` have? What are the column names?

In [ ]:
df_apps.shape

(10841, 12)

In [ ]:
df_apps.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size_MBs', 'Installs', 'Type',
       'Price', 'Content_Rating', 'Genres', 'Last_Updated', 'Android_Ver'],
      dtype='object')

In [ ]:
df_apps.sample(n=5)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
5677,Lark - 24/7 Health Coach,HEALTH_AND_FITNESS,4.10,3405,51.00,"100,000",Free,0,Everyone,Health & Fitness,"July 25, 2018",4.4 and up
1933,Complete Anatomy for Android,MEDICAL,4.10,90,21.00,"1,000",Free,0,Everyone,Medical,"July 11, 2018",7.0 and up
5381,Lire avec Sami et Julie,FAMILY,3.60,569,18.00,"100,000",Free,0,Everyone,Educational;Education,"June 13, 2014",2.2 and up
4755,Fifa World Cup 2018: Photo Frame Editor & DP M...,PHOTOGRAPHY,4.60,666,8.70,"100,000",Free,0,Everyone,Photography,"June 20, 2018",4.0.3 and up
9471,Texas Holdem Poker,GAME,4.00,127831,26.00,"10,000,000",Free,0,Teen,Card,"December 20, 2017",3.0 and up

### Drop Unused Columns

Remove the columns called `Last_Updated` and `Android_Version` from the DataFrame. Won't be used.

In [ ]:
df_apps.drop(['Last_Updated', 'Android_Ver'], axis=1, inplace=True)

In [ ]:
df_apps

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
0,Ak Parti Yardım Toplama,SOCIAL,NaN,0,8.70,0,Paid,$13.99,Teen,Social
1,Ain Arabic Kids Alif Ba ta,FAMILY,NaN,0,33.00,0,Paid,$2.99,Everyone,Education
2,Popsicle Launcher for Android P 9.0 launcher,PERSONALIZATION,NaN,0,5.50,0,Paid,$1.49,Everyone,Personalization
3,Command & Conquer: Rivals,FAMILY,NaN,0,19.00,0,NaN,0,Everyone 10+,Strategy
4,CX Network,BUSINESS,NaN,0,10.00,0,Free,0,Everyone,Business
...,...,...,...,...,...,...,...,...,...,...
10836,Subway Surfers,GAME,4.50,27723193,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade
10837,Subway Surfers,GAME,4.50,27724094,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade
10838,Subway Surfers,GAME,4.50,27725352,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade
10839,Subway Surfers,GAME,4.50,27725352,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade
10840,Subway Surfers,GAME,4.50,27711703,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade

### Find and Remove NaN values in Ratings

How may rows have a NaN value (not-a-number) in the Ratings column? Create DataFrame called `df_apps_clean` that does not include these rows.

In [ ]:
# Count rows with at least one NaN
rows_with_nan = df_apps['Rating'].isnull().sum()
print(f"Number of rows on the rating column with at least one NaN value: {rows_with_nan}")

Number of rows on the rating column with at least one NaN value: 1474

In [ ]:
df_apps_clean = df_apps.dropna()
df_apps_clean.shape
df_apps_clean

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0,Everyone,Medical
28,Ra Ga Ba,GAME,5.00,2,20.00,1,Paid,$1.49,Everyone,Arcade
47,Mu.F.O.,GAME,5.00,2,16.00,1,Paid,$0.99,Everyone,Arcade
82,Brick Breaker BR,GAME,5.00,7,19.00,5,Free,0,Everyone,Arcade
99,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5.00,1,4.60,5,Free,0,Everyone,Medical
...,...,...,...,...,...,...,...,...,...,...
10836,Subway Surfers,GAME,4.50,27723193,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade
10837,Subway Surfers,GAME,4.50,27724094,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade
10838,Subway Surfers,GAME,4.50,27725352,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade
10839,Subway Surfers,GAME,4.50,27725352,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade
10840,Subway Surfers,GAME,4.50,27711703,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade

### Find and Remove Duplicates

Are there any duplicates in data? How many entries can we find for the "Instagram" app?

In [ ]:
df_apps_clean.duplicated().sum()

np.int64(476)

In [ ]:
df_apps_clean.duplicated(subset=['App']).sum()

np.int64(1170)

In [ ]:
df_apps_clean[df_apps_clean['App'] == 'Instagram']

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10806,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social
10808,Instagram,SOCIAL,4.50,66577446,5.30,"1,000,000,000",Free,0,Teen,Social
10809,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social
10810,Instagram,SOCIAL,4.50,66509917,5.30,"1,000,000,000",Free,0,Teen,Social

In [ ]:
(df_apps_clean['App'] == 'Instagram').sum()

np.int64(4)

In [ ]:
# need to specify the subset for identifying duplicates
df_apps_clean = df_apps_clean.drop_duplicates(subset=['App', 'Type', 'Price'])
df_apps_clean
# df_apps_clean[df_apps_clean.App == 'Instagram']

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0,Everyone,Medical
28,Ra Ga Ba,GAME,5.00,2,20.00,1,Paid,$1.49,Everyone,Arcade
47,Mu.F.O.,GAME,5.00,2,16.00,1,Paid,$0.99,Everyone,Arcade
82,Brick Breaker BR,GAME,5.00,7,19.00,5,Free,0,Everyone,Arcade
99,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5.00,1,4.60,5,Free,0,Everyone,Medical
...,...,...,...,...,...,...,...,...,...,...
10824,Google Drive,PRODUCTIVITY,4.40,2731171,4.00,"1,000,000,000",Free,0,Everyone,Productivity
10828,YouTube,VIDEO_PLAYERS,4.30,25655305,4.65,"1,000,000,000",Free,0,Teen,Video Players & Editors
10829,Google Play Movies & TV,VIDEO_PLAYERS,3.70,906384,4.65,"1,000,000,000",Free,0,Teen,Video Players & Editors
10831,Google News,NEWS_AND_MAGAZINES,3.90,877635,13.00,"1,000,000,000",Free,0,Teen,News & Magazines
10835,Subway Surfers,GAME,4.50,27722264,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade

# Find Highest Rated Apps

Identify which apps are the highest rated. What problem might we encounter if we rely exclusively on ratings alone to determine the quality of an app?

In [ ]:
highest_rating = df_apps_clean['Rating'].max()
df_highest_rated = df_apps_clean[df_apps_clean['Rating'] == highest_rating][['App', 'Rating']]
df_highest_rated

                                                   App  Rating
21                                 KBA-EZ Health Guide    5.00
28                                            Ra Ga Ba    5.00
47                                             Mu.F.O.    5.00
82                                    Brick Breaker BR    5.00
99     Anatomy & Physiology Vocabulary Exam Review App    5.00
...                                                ...     ...
2680                               Florida Wildflowers    5.00
2750  Superheroes, Marvel, DC, Comics, TV, Movies News    5.00
3030           CL Keyboard - Myanmar Keyboard (No Ads)    5.00
3115                                        Oración CX    5.00
4058                          Ek Bander Ne Kholi Dukan    5.00

[271 rows x 2 columns]

In [ ]:
# Another way
df_apps_clean.sort_values(by='Rating', ascending=False).head(15)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0,Everyone,Medical
1751,Spine- The dating app,DATING,5.00,5,9.30,500,Free,0,Teen,Dating
1761,Selfie With Champion AJ Style,PHOTOGRAPHY,5.00,2,7.50,500,Free,0,Everyone,Photography
1763,Ag Valley Cooperative,BUSINESS,5.00,6,74.00,500,Free,0,Everyone,Business
1769,Yazdani Cd Center EllahAbad Official App,FAMILY,5.00,8,3.80,500,Free,0,Everyone,Entertainment
1772,Victoria EC,TOOLS,5.00,5,3.80,500,Free,0,Everyone,Tools
1780,CD CHOICE TUBE,FAMILY,5.00,10,5.80,500,Free,0,Everyone,Entertainment
1675,WPBS-DT,FAMILY,5.00,3,6.30,500,Free,0,Everyone,Entertainment
1677,CG FM,FAMILY,5.00,2,6.60,500,Free,0,Everyone,Entertainment
1685,EK Bailey Preaching Conference,EVENTS,5.00,3,30.00,500,Free,0,Everyone,Events
1690,Exam Result BD,FAMILY,5.00,2,2.60,500,Free,0,Everyone,Education
1789,Ek Vote,PRODUCTIVITY,5.00,43,6.20,500,Free,0,Everyone,Productivity
261,Monster Ride Pro,GAME,5.00,1,24.00,10,Free,0,Everyone,Racing
265,FAST EO,EVENTS,5.00,1,6.30,10,Free,0,Everyone,Events
291,AC DC Power Monitor,LIFESTYLE,5.00,1,1.20,10,Paid,$3.04,Everyone,Lifestyle

# Find 5 Largest Apps in terms of Size (MBs)

**Challenge**: What's the size in megabytes (MB) of the largest Android apps in the Google Play Store. Based on the data, do you think there could be limit in place or can developers make apps as large as they please?

In [ ]:
largest_android_size = df_apps_clean['Size_MBs'].max()
df_largest_android_apps = df_apps_clean[df_apps_clean['Size_MBs'] == largest_android_size][['App', 'Size_MBs']]
df_largest_android_apps

# Another way:
# largest = df_apps_clean.nlargest(n=10, columns='Size_MBs')[['App', 'Size_MBs']]
# largest

                                                    App  Size_MBs
1795                               Navi Radiography Pro    100.00
3144                                         Vi Trainer    100.00
4176   Car Crash III Beam DH Real Damage Simulator 2018    100.00
7926                                          Post Bank    100.00
7927                        The Walking Dead: Our World    100.00
7928                      Stickman Legends: Shadow Wars    100.00
8718                  Mini Golf King - Multiplayer Game    100.00
8719                         Draft Simulator for FUT 18    100.00
9942                     Talking Babsy Baby: Baby Games    100.00
9943                              Miami crime simulator    100.00
9944                       Gangster Town: Vice District    100.00
9945                                    Ultimate Tennis    100.00
10295                                   SimCity BuildIt    100.00
10687                            Hungry Shark Evolution    100.00

In [ ]:
df_apps_clean

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0,Everyone,Medical
28,Ra Ga Ba,GAME,5.00,2,20.00,1,Paid,$1.49,Everyone,Arcade
47,Mu.F.O.,GAME,5.00,2,16.00,1,Paid,$0.99,Everyone,Arcade
82,Brick Breaker BR,GAME,5.00,7,19.00,5,Free,0,Everyone,Arcade
99,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5.00,1,4.60,5,Free,0,Everyone,Medical
...,...,...,...,...,...,...,...,...,...,...
10824,Google Drive,PRODUCTIVITY,4.40,2731171,4.00,"1,000,000,000",Free,0,Everyone,Productivity
10828,YouTube,VIDEO_PLAYERS,4.30,25655305,4.65,"1,000,000,000",Free,0,Teen,Video Players & Editors
10829,Google Play Movies & TV,VIDEO_PLAYERS,3.70,906384,4.65,"1,000,000,000",Free,0,Teen,Video Players & Editors
10831,Google News,NEWS_AND_MAGAZINES,3.90,877635,13.00,"1,000,000,000",Free,0,Teen,News & Magazines
10835,Subway Surfers,GAME,4.50,27722264,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade

# Find the 5 App with Most Reviews

Which apps have the highest number of reviews? Are there any paid apps among the top 50?

In [ ]:
highest_reviews = df_apps_clean['Reviews'].max()
df_highest_reviews = df_apps_clean[df_apps_clean['Reviews'] == highest_reviews][['App', 'Reviews']]
df_highest_reviews

            App   Reviews
10805  Facebook  78158306

In [ ]:
top_50_reviews = df_apps_clean.nlargest(n=50, columns='Reviews')[['App', 'Reviews', 'Price']]
top_50_reviews

                                                     App   Reviews Price
10805                                           Facebook  78158306     0
10785                                 WhatsApp Messenger  69119316     0
10806                                          Instagram  66577313     0
10784           Messenger – Text and Video Chat for Free  56642847     0
10650                                     Clash of Clans  44891723     0
10744            Clean Master- Space Cleaner & Antivirus  42916526     0
10835                                     Subway Surfers  27722264     0
10828                                            YouTube  25655305     0
10746  Security Master - Antivirus, VPN, AppLock, Boo...  24900999     0
10584                                       Clash Royale  23133508     0
10763                                   Candy Crush Saga  22426677     0
10770        UC Browser - Fast Download Private & Secure  17712922     0
10735                                           Snapchat  17014787     0
10489    360 Security - Free Antivirus, Booster, Cleaner  16771865     0
10731                                     My Talking Tom  14891223     0
10594                                        8 Ball Pool  14198297     0
10302  DU Battery Saver - Battery Charger & Battery Life  13479633     0
10354                        BBM - Free Calls & Messages  12842860     0
10549  Cache Cleaner-DU Speed Booster (booster & clea...  12759663     0
10757                                            Twitter  11667403     0
10721                                    Viber Messenger  11334799     0
10578                                     Shadow Fight 2  10979062     0
10813                                      Google Photos  10858556     0
10724                        LINE: Free Calls & Messages  10790289     0
10717                                                Pou  10485308     0
10792                      Skype - free IM & video calls  10484169     0
10628                                         Pokémon GO  10424925     0
10388           Minion Rush: Despicable Me Official Game  10216538     0
10694                                            Yes day  10055521     0
10695                                            Hay Day  10053186     0
10644                           Dream League Soccer 2018   9882639     0
10696                                  My Talking Angela   9881829     0
10660             VivaVideo - Video Editor & Photo Movie   9879473     0
10786                       Google Chrome: Fast & Secure   9642995     0
10817                          Maps - Navigate & Explore   9235155     0
10672                                  Hill Climb Racing   8923587     0
10734                                      Facebook Lite   8606259     0
10649                                Asphalt 8: Airborne   8389714     0
10699                          Mobile Legends: Bang Bang   8219586     0
10322  Battery Doctor-Battery Life Saver & Battery Co...   8190074     0
10396                                     Piano Tiles 2™   8118880     0
10777                                       Temple Run 2   8118609     0
10822                                             Google   8033493     0
10359  Truecaller: Caller ID, SMS spam blocking & Dialer   7820209     0
10711                         SHAREit - Transfer & Share   7790693     0
10389   Sniper 3D Gun Shooter: Free Shooting Games - FPS   7671249     0
10676                                   Farm Heroes Saga   7614130     0
10576   PicsArt Photo Studio: Collage Maker & Pic Editor   7594559     0
10461  PhotoGrid: Video & Pic Collage Maker, Photo Ed...   7529865     0
10502   GO Launcher - 3D parallax Themes & HD Wallpapers   7464996     0

# Plotly Pie and Donut Charts - Visualise Categorical Data: Content Ratings

In [ ]:
ratings = df_apps_clean.Content_Rating.value_counts()
ratings

Content_Rating
Everyone           6621
Teen                912
Mature 17+          357
Everyone 10+        305
Adults only 18+       3
Unrated               1
Name: count, dtype: int64

In [ ]:
fig = px.pie(labels=ratings.index, values=ratings.values, title='Content Rating', names=ratings.index)
fig.update_traces(textposition='outside', textinfo='percent+label')

fig.show()

In [ ]:
# Donut
fig = px.pie(
    labels=ratings.index,
    values=ratings.values,
    title='Content Rating',
    names=ratings.index,
    hole=0.6)
fig.update_traces(textposition='inside', textfont_size = 15, textinfo = 'percent')

fig.show()

# Numeric Type Conversion: Examine the Number of Installs

How many apps had over 1 billion (that's right - BILLION) installations? How many apps just had a single install?

Check the datatype of the Installs column.

Count the number of apps at each level of installations.

Convert the number of installations (the Installs column) to a numeric data type.

In [ ]:
df_apps_clean.dtypes

App                object
Category           object
Rating            float64
Reviews             int64
Size_MBs          float64
Installs           object
Type               object
Price              object
Content_Rating     object
Genres             object
dtype: object

In [ ]:
# Count the number of apps at each level of installations.
install_count = df_apps_clean[['App', 'Installs']].groupby('Installs').count()
install_count

                App
Installs
1                 3
1,000           698
1,000,000      1417
1,000,000,000    20
10               69
10,000          988
10,000,000      933
100             303
100,000        1096
100,000,000     189
5                 9
5,000           425
5,000,000       607
50               56
50,000          457
50,000,000      202
500             199
500,000         504
500,000,000      24

In [ ]:
# Convert the number of installations (the Installs column) to a numeric data type.
df_apps_clean = df_apps_clean.copy()
# df_apps_clean['Installs'] = df_apps_clean['Installs'].str.replace(',', '')

In [ ]:
df_apps_clean['Installs'] = pd.to_numeric(df_apps_clean['Installs'])
df_apps_clean[['App', 'Installs']].groupby('Installs').count().sort_values(by='Installs', ascending=False)

             App
Installs
1000000000    20
500000000     24
100000000    189
50000000     202
10000000     933
5000000      607
1000000     1417
500000       504
100000      1096
50000        457
10000        988
5000         425
1000         698
500          199
100          303
50            56
10            69
5              9
1              3

# Find the Most Expensive Apps, Filter out the Junk, and Calculate a (ballpark) Sales Revenue Estimate

Let's examine the Price column more closely.

Convert the price column to numeric data. Then investigate the top 20 most expensive apps in the dataset.

Remove all apps that cost more than $250 from the `df_apps_clean` DataFrame.

Add a column called 'Revenue_Estimate' to the DataFrame. This column should hold the price of the app times the number of installs. What are the top 10 highest grossing paid apps according to this estimate? Out of the top 10 highest grossing paid apps, how many are games?

In [ ]:
df_apps_clean2 = df_apps_clean.copy()
df_apps_clean2['Price'] = pd.to_numeric(df_apps_clean2['Price'].str.strip('$'))
df_apps_clean2[['App','Price']].sort_values(by='Price', ascending=False).head(20)

                                 App  Price
3946        I'm Rich - Trump Edition 400.00
2394                      I am Rich! 399.99
2461              I AM RICH PRO PLUS 399.99
1331          most expensive app (H) 399.99
3145              I am rich(premium) 399.99
2775                   I Am Rich Pro 399.99
5765                       I am rich 399.99
3221                  I am Rich Plus 399.99
3554                      💎 I'm rich 399.99
3114                       I am Rich 399.99
4606               I Am Rich Premium 399.99
1946  I am rich (Most expensive app) 399.99
3897                       I Am Rich 389.99
2193             I am extremely Rich 379.99
3856                   I am rich VIP 299.99
2281       Vargo Anesthesia Mega App  79.99
1407                    LTC AS Legal  39.99
2629                I am Rich Person  37.99
2481         A Manual of Acupuncture  33.99
2207                        EMT PASS  29.99

### The most expensive apps sub $250

In [ ]:
# Remove all apps that cost more than $250 from the df_apps_clean DataFrame.
df_apps_clean3 = df_apps_clean2.copy()
df_apps_clean3 = df_apps_clean2[df_apps_clean2['Price'] <= 250]
df_apps_clean3.sort_values(by='Price', ascending=False)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
2281,Vargo Anesthesia Mega App,MEDICAL,4.60,92,32.00,1000,Paid,79.99,Everyone,Medical
1407,LTC AS Legal,MEDICAL,4.00,6,1.30,100,Paid,39.99,Everyone,Medical
2629,I am Rich Person,LIFESTYLE,4.20,134,1.80,1000,Paid,37.99,Everyone,Lifestyle
2481,A Manual of Acupuncture,MEDICAL,3.50,214,68.00,1000,Paid,33.99,Everyone,Medical
504,AP Art History Flashcards,FAMILY,5.00,1,96.00,10,Paid,29.99,Mature 17+,Education
...,...,...,...,...,...,...,...,...,...,...
4609,China Town Auto Theft 2,GAME,4.10,364,67.00,50000,Free,0.00,Everyone 10+,Action
4610,Intellijoy Early Learning Academy,FAMILY,4.30,160,67.00,50000,Free,0.00,Everyone,Education;Education
4611,EXO-L Amino for EXO Fans,SOCIAL,4.90,5677,67.00,50000,Free,0.00,Teen,Social
4612,BC Liquor Stores,LIFESTYLE,3.70,492,4.30,50000,Free,0.00,Everyone,Lifestyle
780,CI On The Go,NEWS_AND_MAGAZINES,3.00,2,14.00,100,Free,0.00,Everyone,News & Magazines

### Highest Grossing Paid Apps (ballpark estimate)

In [ ]:
# What are the top 10 highest-grossing paid apps according to this estimate? Out of the top 10, how many are games?
df_apps_clean3 = df_apps_clean3.copy()
df_apps_clean3['Revenue_Estimate'] = df_apps_clean3['Price'] * df_apps_clean3['Installs']
df_apps_clean3
df_apps_clean3[['App', 'Category', 'Installs', 'Price', 'Revenue_Estimate']].sort_values(by='Revenue_Estimate', ascending=False).head(10)

,App,Category,Installs,Price,Revenue_Estimate
9220,Minecraft,FAMILY,10000000,6.99,"69,900,000.00"
8825,Hitman Sniper,GAME,10000000,0.99,"9,900,000.00"
7151,Grand Theft Auto: San Andreas,GAME,1000000,6.99,"6,990,000.00"
7477,Facetune - For Free,PHOTOGRAPHY,1000000,5.99,"5,990,000.00"
7977,Sleep as Android Unlock,LIFESTYLE,1000000,5.99,"5,990,000.00"
6594,DraStic DS Emulator,GAME,1000000,4.99,"4,990,000.00"
6082,Weather Live,WEATHER,500000,5.99,"2,995,000.00"
6746,Card Wars - Adventure Time,FAMILY,1000000,2.99,"2,990,000.00"
7633,Five Nights at Freddy's,GAME,1000000,2.99,"2,990,000.00"
7954,Bloons TD 5,FAMILY,1000000,2.99,"2,990,000.00"

In [ ]:
df_apps_clean3.Category.nunique()
top10_category = df_apps_clean3.Category.value_counts()[:10]
top10_category

Category
FAMILY             1606
GAME                910
TOOLS               719
PRODUCTIVITY        301
PERSONALIZATION     298
LIFESTYLE           297
FINANCE             296
MEDICAL             292
PHOTOGRAPHY         263
BUSINESS            262
Name: count, dtype: int64

# Plotly Bar Charts & Scatter Plots: Analysing App Categories

In [ ]:
bar = px.bar(x= top10_category.index, y=top10_category.values)

bar.show()

In [ ]:
# Let's visualize not just the total number of apps in the category but how often apps are downloaded in that category
category_installs = df_apps_clean3.groupby('Category').agg({'Installs': pd.Series.sum})
category_installs.sort_values('Installs', ascending=True, inplace=True)
category_installs

                        Installs
Category
EVENTS                  15949410
BEAUTY                  26916200
PARENTING               31116110
MEDICAL                 39162676
COMICS                  44931100
LIBRARIES_AND_DEMO      52083000
AUTO_AND_VEHICLES       53129800
HOUSE_AND_HOME          97082000
ART_AND_DESIGN         114233100
DATING                 140912410
FOOD_AND_DRINK         211677750
EDUCATION              352852000
WEATHER                361096500
FINANCE                455249400
MAPS_AND_NAVIGATION    503267560
LIFESTYLE              503611120
BUSINESS               692018120
SPORTS                1096431465
HEALTH_AND_FITNESS    1134006220
SHOPPING              1400331540
PERSONALIZATION       1532352930
BOOKS_AND_REFERENCE   1665791655
ENTERTAINMENT         2113660000
NEWS_AND_MAGAZINES    2369110650
TRAVEL_AND_LOCAL      2894859300
VIDEO_PLAYERS         3916897200
FAMILY                4437554490
PHOTOGRAPHY           4649143130
SOCIAL                5487841475
PRODUCTIVITY          5788070180
TOOLS                 8099724500
COMMUNICATION        11039241530
GAME                 13858762717

In [ ]:
h_bar = px.bar(x=category_installs.Installs,
               y=category_installs.index,
               orientation='h',
               title='Category Popularity')

h_bar.update_layout(xaxis_title='Number of Downloads',
                    yaxis_title='Category')

h_bar.show()

In [ ]:
df_category_vs_apps = df_apps_clean3.groupby('Category').agg({
    'App': 'count',
    'Installs': 'sum'
})

df_category_vs_apps.sort_values('Installs', ascending=False, inplace=True)
df_category_vs_apps

# Another way:
# cat_number = df_apps_clean.groupby('Category').agg({'App': pd.Series.count})
# cat_merged_df = pd.merge(cat_number, category_installs, on='Category', how="inner")
# print(f'The dimensions of the DataFrame are: {cat_merged_df.shape}')
# cat_merged_df.sort_values('Installs', ascending=False)

                      App     Installs
Category
GAME                  910  13858762717
COMMUNICATION         257  11039241530
TOOLS                 719   8099724500
PRODUCTIVITY          301   5788070180
SOCIAL                203   5487841475
PHOTOGRAPHY           263   4649143130
FAMILY               1606   4437554490
VIDEO_PLAYERS         148   3916897200
TRAVEL_AND_LOCAL      187   2894859300
NEWS_AND_MAGAZINES    204   2369110650
ENTERTAINMENT         102   2113660000
BOOKS_AND_REFERENCE   169   1665791655
PERSONALIZATION       298   1532352930
SHOPPING              180   1400331540
HEALTH_AND_FITNESS    243   1134006220
SPORTS                260   1096431465
BUSINESS              262    692018120
LIFESTYLE             297    503611120
MAPS_AND_NAVIGATION   118    503267560
FINANCE               296    455249400
WEATHER                72    361096500
EDUCATION             118    352852000
FOOD_AND_DRINK         94    211677750
DATING                134    140912410
ART_AND_DESIGN         61    114233100
HOUSE_AND_HOME         62     97082000
AUTO_AND_VEHICLES      73     53129800
LIBRARIES_AND_DEMO     64     52083000
COMICS                 54     44931100
MEDICAL               292     39162676
PARENTING              50     31116110
BEAUTY                 42     26916200
EVENTS                 45     15949410

In [ ]:
scatter = px.scatter(df_category_vs_apps, # data
                    x='App', # column name
                    y='Installs',
                    title='Category Concentration',
                    size='App',
                    hover_name=df_category_vs_apps.index,
                    color='Installs')

scatter.update_layout(xaxis_title="Number of Apps (Lower=More Concentrated)",
                      yaxis_title="Installs",
                      yaxis=dict(type='log'))

scatter.show()

### Vertical Bar Chart - Highest Competition (Number of Apps)

### Horizontal Bar Chart - Most Popular Categories (Highest Downloads)

### Category Concentration - Downloads vs. Competition

In [ ]:
df_apps_clean3

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Revenue_Estimate
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0.00,Everyone,Medical,0.00
28,Ra Ga Ba,GAME,5.00,2,20.00,1,Paid,1.49,Everyone,Arcade,1.49
47,Mu.F.O.,GAME,5.00,2,16.00,1,Paid,0.99,Everyone,Arcade,0.99
82,Brick Breaker BR,GAME,5.00,7,19.00,5,Free,0.00,Everyone,Arcade,0.00
99,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5.00,1,4.60,5,Free,0.00,Everyone,Medical,0.00
...,...,...,...,...,...,...,...,...,...,...,...
10824,Google Drive,PRODUCTIVITY,4.40,2731171,4.00,1000000000,Free,0.00,Everyone,Productivity,0.00
10828,YouTube,VIDEO_PLAYERS,4.30,25655305,4.65,1000000000,Free,0.00,Teen,Video Players & Editors,0.00
10829,Google Play Movies & TV,VIDEO_PLAYERS,3.70,906384,4.65,1000000000,Free,0.00,Teen,Video Players & Editors,0.00
10831,Google News,NEWS_AND_MAGAZINES,3.90,877635,13.00,1000000000,Free,0.00,Teen,News & Magazines,0.00
10835,Subway Surfers,GAME,4.50,27722264,76.00,1000000000,Free,0.00,Everyone 10+,Arcade,0.00

# Extracting Nested Data from a Column

How many different types of genres are there? Can an app belong to more than one genre?

In [ ]:
df_apps_multiple_genres = df_apps_clean[df_apps_clean["Genres"].str.contains("Education")]
df_apps_multiple_genres

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
174,CG Jobs,FAMILY,5.00,8,14.00,10,Free,0,Everyone,Education
179,Bh Public School,FAMILY,5.00,2,8.70,10,Free,0,Everyone,Education
184,BU Study,FAMILY,5.00,7,5.60,10,Free,0,Everyone,Education
312,30WPM Amateur ham radio Koch CW Morse code tra...,FAMILY,5.00,1,3.70,10,Paid,$1.49,Everyone,Education
357,Speech Therapy: F,FAMILY,1.00,1,16.00,10,Paid,$2.99,Everyone,Education
...,...,...,...,...,...,...,...,...,...,...
9920,ClassDojo,EDUCATION,4.40,148550,59.00,10000000,Free,0,Everyone,Education;Education
9924,COOKING MAMA Let's Cook!,FAMILY,4.30,528745,59.00,10000000,Free,0,Everyone,Educational;Pretend Play
10202,Toca Kitchen 2,FAMILY,4.50,1014822,56.00,50000000,Free,0,Everyone,Educational;Pretend Play
10244,LEGO® Juniors Create & Cruise,FAMILY,4.10,673203,73.00,50000000,Free,0,Everyone,Educational;Action & Adventure
10372,Duolingo: Learn Languages Free,EDUCATION,4.70,6289924,6.95,100000000,Free,0,Everyone,Education;Education

In [ ]:
df_apps_multiple_genres.Genres.value_counts()

Genres
Education                         429
Education;Education                36
Educational;Education              35
Educational                        32
Education;Pretend Play             17
Educational;Pretend Play           12
Education;Creativity                6
Educational;Brain Games             6
Educational;Creativity              5
Education;Action & Adventure        4
Education;Brain Games               3
Simulation;Education                3
Educational;Action & Adventure      3
Education;Music & Video             3
Parenting;Education                 3
Casual;Education                    3
Books & Reference;Education         2
Lifestyle;Education                 1
Puzzle;Education                    1
Health & Fitness;Education          1
Strategy;Education                  1
Entertainment;Education             1
Tools;Education                     1
Adventure;Education                 1
Name: count, dtype: int64

In [ ]:
separated_genres_df = df_apps_multiple_genres.Genres.str.split(";")
separated_genres_df

174                            [Education]
179                            [Education]
184                            [Education]
312                            [Education]
357                            [Education]
                       ...
9920                [Education, Education]
9924           [Educational, Pretend Play]
10202          [Educational, Pretend Play]
10244    [Educational, Action & Adventure]
10372               [Education, Education]
Name: Genres, Length: 609, dtype: object

In [ ]:
# Using expand to have values in different columns instead of same
separated_genres_df = df_apps_multiple_genres.Genres.str.split(";", expand=True)
separated_genres_df

                 0                   1
174      Education                None
179      Education                None
184      Education                None
312      Education                None
357      Education                None
...            ...                 ...
9920     Education           Education
9924   Educational        Pretend Play
10202  Educational        Pretend Play
10244  Educational  Action & Adventure
10372    Education           Education

[609 rows x 2 columns]

In [ ]:
# Use stack to put column 1 belown column 0 to calculate more efficiently
stacked_genres = separated_genres_df.stack()
stacked_genres

174    0             Education
179    0             Education
184    0             Education
312    0             Education
357    0             Education
                   ...
10202  1          Pretend Play
10244  0           Educational
       1    Action & Adventure
10372  0             Education
       1             Education
Length: 757, dtype: object

In [ ]:
# Get the count by Individual Genre
stacked_genres.value_counts()

Education             587
Educational            93
Pretend Play           29
Creativity             11
Brain Games             9
Action & Adventure      7
Music & Video           3
Casual                  3
Parenting               3
Simulation              3
Books & Reference       2
Lifestyle               1
Health & Fitness        1
Puzzle                  1
Strategy                1
Entertainment           1
Tools                   1
Adventure               1
Name: count, dtype: int64

In [ ]:
# Split the strings on the semi-colon and then .stack them.
stack = df_apps_clean3.Genres.str.split(';', expand=True).stack()
stack
print(f'We now have a single column with shape: {stack.shape}')
num_genres = stack.value_counts()
num_genres
print(f'Number of genres: {len(num_genres)}')

We now have a single column with shape: (8564,)
Number of genres: 53

In [ ]:
num_genres

Tools                      719
Education                  587
Entertainment              498
Action                     304
Productivity               301
Personalization            298
Lifestyle                  298
Finance                    296
Medical                    292
Sports                     270
Photography                263
Business                   262
Communication              258
Health & Fitness           245
Casual                     216
News & Magazines           204
Social                     203
Simulation                 200
Travel & Local             187
Arcade                     185
Shopping                   180
Books & Reference          171
Video Players & Editors    150
Dating                     134
Puzzle                     124
Maps & Navigation          118
Role Playing               111
Racing                     103
Action & Adventure          96
Strategy                    95
Food & Drink                94
Educational                 93
Adventure                   78
Auto & Vehicles             73
Weather                     72
Pretend Play                68
Brain Games                 65
Libraries & Demo            64
House & Home                62
Art & Design                62
Board                       57
Comics                      54
Parenting                   50
Card                        46
Events                      45
Beauty                      42
Casino                      37
Music & Video               31
Creativity                  31
Trivia                      28
Word                        22
Music                       21
Music & Audio                1
Name: count, dtype: int64

# Colour Scales in Plotly Charts - Competition in Genres

In [ ]:
bar = px.bar(
    num_genres,
    x=num_genres.index[:15],
    y=num_genres.values[:15],
    title='Top Genres',
    hover_name=num_genres.index[:15],
    color=num_genres.values[:15],  # map color to values
    color_continuous_scale=px.colors.sequential.Agsunset
)

bar.update_layout(
    xaxis_title='Genre',
    yaxis_title='Number of Apps',
    xaxis_tickangle=-45,
    coloraxis_showscale=False,

)

bar.show()

# Grouped Bar Charts: Free vs. Paid Apps per Category

In [ ]:
df_apps_clean3.Type.value_counts()

Type
Free    7595
Paid     589
Name: count, dtype: int64

In [ ]:
# Use as_index to push our data into columns rather than index
df_free_vs_paid = df_apps_clean3.groupby(['Category', 'Type'], as_index=False).agg({'App': pd.Series.count})
df_free_vs_paid.sort_values(by='App', ascending=False, inplace=True)

             Category  Type   App
19             FAMILY  Free  1456
25               GAME  Free   834
53              TOOLS  Free   656
21            FINANCE  Free   289
31          LIFESTYLE  Free   284
..                ...   ...   ...
24     FOOD_AND_DRINK  Paid     2
50             SOCIAL  Paid     2
40          PARENTING  Paid     2
48           SHOPPING  Paid     2
3   AUTO_AND_VEHICLES  Paid     1

[61 rows x 3 columns]

In [ ]:
# Create visualization
g_bar = px.bar(df_free_vs_paid,
               x='Category',
               y='App',
               title='Free vs Paid Apps by Category',
               color='Type',
               barmode='group')

g_bar.update_layout(xaxis_title='Category',
                    yaxis_title='Number of Apps',
                    xaxis={'categoryorder': 'total descending'},
                    yaxis=dict(type='log'))

g_bar.show()

In [ ]:
df_apps_clean3.sort_values('Revenue_Estimate', ascending=False)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Revenue_Estimate
9220,Minecraft,FAMILY,4.50,2376564,19.00,10000000,Paid,6.99,Everyone 10+,Arcade;Action & Adventure,"69,900,000.00"
8825,Hitman Sniper,GAME,4.60,408292,29.00,10000000,Paid,0.99,Mature 17+,Action,"9,900,000.00"
7151,Grand Theft Auto: San Andreas,GAME,4.40,348962,26.00,1000000,Paid,6.99,Mature 17+,Action,"6,990,000.00"
7477,Facetune - For Free,PHOTOGRAPHY,4.40,49553,48.00,1000000,Paid,5.99,Everyone,Photography,"5,990,000.00"
7977,Sleep as Android Unlock,LIFESTYLE,4.50,23966,0.85,1000000,Paid,5.99,Everyone,Lifestyle,"5,990,000.00"
...,...,...,...,...,...,...,...,...,...,...,...
4632,Inputting Plus: Ctrl + Z/F/C/V,PRODUCTIVITY,4.20,1117,3.00,50000,Free,0.00,Everyone,Productivity,0.00
4633,Drink-O-Tron The Drinking Game,GAME,4.10,140,45.00,50000,Free,0.00,Mature 17+,Card,0.00
4635,EZ Quran,BOOKS_AND_REFERENCE,4.60,595,8.50,50000,Free,0.00,Everyone,Books & Reference,0.00
4636,Berner Zeitung,NEWS_AND_MAGAZINES,3.40,736,8.50,50000,Free,0.00,Teen,News & Magazines,0.00
870,DV Statistics,SOCIAL,4.20,6,2.70,100,Free,0.00,Everyone,Social,0.00

# Plotly Box Plots: Lost Downloads for Paid Apps

Create a box plot that shows the number of Installs for free versus paid apps. How does the median number of installations compare? Is the difference large or small?

In [ ]:
box = px.box(
    df_apps_clean3,
    x='Type',
    y='Installs',
    title='How Many Downloads Are Paid Apps Giving Up?',
    color='Type',
    notched=True,
    boxmode='group',
    points="all"
)

box.update_layout(xaxis_title='Type',
                    yaxis_title='Installs',
                    yaxis=dict(type='log'))

box.show()

# Plotly Box Plots: Revenue by App Category

Looking at the hover text, how much does the median app earn in the Tools category? If developing an Android app costs $30,000 or thereabouts, does the average photography app recoup its development costs?

In [ ]:
paid_apps = df_apps_clean3[df_apps_clean3['Type'] == 'Paid']

box = px.box(paid_apps,
    x='Category',
    y='Revenue_Estimate',
    title='How Much Can Paid Apps Earn'
)

box.update_layout(xaxis_title='Category',
                  yaxis_title='Paid App Ballpark Revenue',
                  xaxis={'categoryorder':'min ascending'},
                  yaxis=dict(type='log')
                  )

box.show()

# How Much Can You Charge? Examine Paid App Pricing Strategies by Category

What is the median price price for a paid app? Then compare pricing by category by creating another box plot. But this time examine the prices (instead of the revenue estimates) of the paid apps.

In [ ]:
df_median_price = df_apps_clean3[df_apps_clean3['Price'] > 0]
df_median_price['Price'].sort_values(ascending=False)

2281   79.99
1407   39.99
2629   37.99
2481   33.99
2207   29.99
        ...
7917    0.99
7957    0.99
7928    0.99
47      0.99
8825    0.99
Name: Price, Length: 589, dtype: float64

In [ ]:
#median value
df_median_price['Price'].median()

2.99

In [ ]:
box = px.box(df_median_price,
    x='Category',
    y='Price',
    title='Price per Categoy'
)

box.update_layout(xaxis_title='Category',
                  yaxis_title='Paid App Price',
                  xaxis={'categoryorder':'max descending'},
                  yaxis=dict(type='log')
                  )

box.show()